name: datn_test
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-143.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_clean_calendar: ^1.1.0
  line_awesome_flutter: ^2.0.0
  animated_theme_switcher: ^2.0.10
  flutter_svg: ^0.23.0
  http: ^0.13.4
  flutter_pdfview: ^1.3.2
  bot_toast: ^4.0.3
  syncfusion_flutter_pdfviewer: ^21.2.3
  timer_count_down: ^2.2.2
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.3
  fluttertoast: ^8.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/avatar.png
    - assets/pdf/a.pdf
